function outPages = evaluatePageRelevance(pages)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

    %% Initialization
    options = {
        'register summary','register map','digital interface','data conversion', ...
        'initialization and reset','timing','interrupt alert','fifo'
        };

    %% 
    text = lower(extractTextFrom(pages));
    text = regexprep(text, '(?m)^\s*(#+|-)\s*', '');
    words = arrayfun(@(s) regexp(s,'\S+','match'),text,'UniformOutput',false);
    wordCounts = cellfun(@numel,words);
    
    %% 
    for i = 1:numel(options)
        option = options{i};
        if strcmp(option,'register summary')
            scoreField = 'summary_title_counts';
        else
            scoreField = [regexprep(option,' ','_') '_score'];
        end

        % [pages.(scoreField)] = deal(0);
        statusField = ['has_' regexprep(option,' ','_')];
        for j = 1:numel(pages)
            pages(j).classification.(statusField) = false;
        end
        
        [idx,pageScores] = findRelevantPageRanges(text,wordCounts,option);
        % scoreCell = num2cell(pageScores);
        % [pages.(scoreField)] = scoreCell{:};
        for j = idx
            pages(j).classification.(statusField) = true;
        end
    end
    
    %% Output
    outPages = pages;
end

function [idx,pageScores] = findRelevantPageRanges(text,wordCounts,option)
    %%
    keywords = selectKeyword(option);
    if strcmp(option,'register summary')
        titleFreqMatrix = countQueryHitsByPage(keywords,text);
        pageScores = sum(titleFreqMatrix,2);
        idx = find(pageScores>0)';   
        return
    else
        freqMatrix = countQueryHitsByPage(keywords,text);
        pageScores = computeBM25score(freqMatrix,wordCounts);
    end
    
    tempRanges = selectRange(pageScores,option);

    if isempty(tempRanges)
        idx = [];
        return
    end
    %% 
    for i = 1:numel(tempRanges)
        lastPage = tempRanges{i}(end);
        if lastPage == numel(pageScores)
            continue;
        end

        if pageScores(lastPage+1)>0
            tempRanges{i} = [tempRanges{i} lastPage+1];
        end
    end
    
    %% Merge overlapping or adjacent page ranges.
    allPageNum = unique([tempRanges{:}]);
    breakIdx = find(diff(allPageNum) > 1);
    startIdx = [1, breakIdx + 1];
    endIdx = [breakIdx, numel(allPageNum)];

    pageRanges = arrayfun(@(x, y) allPageNum(x:y), startIdx, endIdx, ...
        'UniformOutput', false);
    idx = [pageRanges{:}];
end

function freqMatrix = countQueryHitsByPage(query,allTexts)
    freqCell = arrayfun(@(x) countQueryHits(query,x),allTexts,'UniformOutput',false);
    freqMatrix = vertcat(freqCell{:});
end

function freq = countQueryHits(query,oneText)
    query = query(:).';
    matchPositions = regexp(oneText,query);
    %matchWord = regexp(oneText,query,'match');  %------debug-------
    %appendDebugData(matchWord,'matchWord');     %------debug-------
    freq = cellfun(@numel,matchPositions);
    freq = freq(:).';
end

function idf = computeInvDocFreq(freqMatrix)
    nPages = size(freqMatrix, 1);
    freqMask = freqMatrix>0;
    docFreq = sum(freqMask,1);
    idf = log(1+(nPages-docFreq+0.5)./(docFreq+0.5));
end

function pageScores = computeBM25score(freqMatrix,wordCounts)
    idf = computeInvDocFreq(freqMatrix);
    idf = idf(:)';
    docLength = wordCounts(:);
    avgDocLength = mean(wordCounts);
    k1 = 1.5;
    b = 0.75;
    
    if avgDocLength == 0
        avgDocLength = 1;
    end
    
    lengthNorm = 1 - b + b*docLength/avgDocLength;
    scoreMatrix = (k1 + 1)*idf.*freqMatrix./(freqMatrix + k1.*lengthNorm);
    pageScores = sum(scoreMatrix,2);
    pageScores = pageScores';
end

function [m,n] = setParameter(option)

    switch option
        case 'register map'
            [m,n] = deal(2,2);
        case 'digital interface'
            [m,n] = deal(1,1);
        case 'data conversion'
            [m,n] = deal(1,1);
        case 'initialization and reset'
            [m,n] = deal(1,1);
        case 'timing'
            [m,n] = deal(1,1);
        case 'interrupt alert'
            [m,n] = deal(1,1);
        case 'fifo'
            [m,n] = deal(1,1);
        otherwise
            error('Unknown option: %s', option);
    end
end

function pageRanges = selectRange(pageScores,option)
% Extract page ranges while allowing gaps of up to m consecutive low-score pages.
    
    if isempty(pageScores) || max(pageScores) <= 0
        pageRanges = {};
        return
    end
    
    %%
    [m,n] = setParameter(option);
    negativeMask = (pageScores < 0.2*max(pageScores));
    d = diff([0 negativeMask 0]);
    zStartIdx = find(d == 1);             
    zEndIdx = find(d == -1) - 1;   
    
    invalid = (zEndIdx - zStartIdx + 1) > m;
    invalidStart = zStartIdx(invalid);
    invalidEnd = zEndIdx(invalid);
    startIdx = 1;
    pageRanges = {};
    
    for i = 1:numel(invalidStart)
        endIdx = invalidStart(i) - 1;
        
        if endIdx-startIdx +1 >= n && startIdx <= endIdx
            pageRanges{end+1} = [startIdx endIdx];
        end
        
        startIdx = invalidEnd(i)+1;
    end
    
    if numel(pageScores)-startIdx + 1 >= n
        pageRanges{end+1} = [startIdx numel(pageScores)];
    end
    %%
    for i = 1:numel(pageRanges)
        pageRanges{i} = pageRanges{i}(1):pageRanges{i}(2);
    end
end

function keywords = selectKeyword(option)
%select keywords depend on option
    option = lower(option);

    switch(option)
        case 'register summary'
            keywords = { ...
                ['reg\.?(?:isters?)\s+' ...
                '(?:maps?|mappings?|descriptions?|tables?|lists?|definitions?|overviews?|summar(?:y|ies)|references?)'], ...
                
                ['address(?:es)?\s+' ...
                '(?:maps?|mappings?|descriptions?|tables?|lists?|definitions?|overviews?|summar(?:y|ies)|references?)'],  ...
                
                'memory\s+map' ...
                };
        case 'register map'
            keywords = {...
                '\<addr\.?\>',...
                '\<address\>', ...
                '\<bank\>', ...
                '(?<!-)\<bits?(?:\s+|-\s*)(?:fields?|descriptions?)\>', ...
                '\<bits?\s*\d+(?:\s*-\s*\d+|\s*:\s*\d+)?\>', ...
                '\<bits?\>(?!\s*[-]?\s*(?:fields?|descriptions?))(?!\s*\d)', ...
                '(?<!\<bit )(?<!\<bits )(?<!\<bit-)(?<!\<bits-)(?<!\<bit- )(?<!\<bits- )\<fields?\>', ...
                '\<reg\.?\>', ...
                '\<registers?\>', ...
                '\<registers?\s*names?\>', ...
                '\<registers?\s*pointers?\>', ...
                '\<registers?\s*addr(?:\.|ess(?:es)?)\>', ...
                '\<hex\>', ...
                '\<decimal\>', ...
                '\<dec\.?\>', ...
                'initial value', ...
                'default value',...
                'reset value',...
                '\<(?:r\s*/\s*w|w\s*/\s*r|r\s*/\s*o|w\s*/\s*o|r\s*w|w\s*r|r\s*o|w\s*o|r|w)\>', ...
                'read\s*/\s*write', ...
                'write\s*/\s*read', ...
                'read only', ...
                'write only', ...
                'readable', ...
                'writable', ...
                '(?<!all rights )\<reserved\>', ...
                '0x[0-9a-f]{2}', ...
                '\<[0-9a-fA-F]{2}h\>', ...
                '\<(?:[01]{4}\s?)+\>'
                };
        case 'digital interface'
            keywords = {...
                '\<(?:digital|serial|communication|bus|host)\s+interfaces?\>', ...
                '\<(?:communications?|interfaces?)\s+protocols?\>', ...
                '\<serial\s+bus\>', ...
                '(?:i2c|i\s*2\s*c|i²c)', ...
                'spi', ...
                'i3c', ...
                '\<(?:slave|device)\s+address\>', ...
                '\<(?:7\s*-\s*bit|10\s*-\s*bit)\s+address\>', ...
                '\<(?:start|stop)\s+condition\>', ...
                '\<repeated\s+start\>', ...
                '\<ack(?:nowledge)?\>', ...
                '\<nack\>', ...
                '\<scl\>', ...
                '\<sda\>', ...
                '\<(?:chip|slave)\s+select\>', ...
                '\<cs\>', ...
                '\<ss\>', ...
                '\<sclk\>', ...
                '\<mosi\>', ...
                '\<miso\>', ...
                '\<sdi\>', ...
                '\<sdo\>', ...
                '\<cpol\>', ...
                '\<cpha\>', ...
                '\<spi\s+mode\>', ...
                '\<(?:3|4)\s*-\s*wire\>', ...
                '\<(?:read|write)\s+transaction\>', ...
                '\<(?:read|write)\s+operation\>', ...
                '\<(?:read|write)\s+sequence\>', ...
                '\<register\s+(?:read|write)\>', ...
                '\<burst\s+(?:read|write)\>', ...
                '\<auto\s+increment\>', ...
                '\<address\s+increment\>', ...
                '\<timing\s+diagram\>', ...
                '\<timing\s+requirements?\>', ...
                '\<bus\s+timing\>', ...
                '\<clock\s+frequency\>', ...
                '\<serial\s+clock\>', ...
                '\<data\s+frame\>', ...
                '\<frame\s+format\>', ...
                '\<(?:command|address|data)\s+byte\>', ...
                '\<(?:msb|lsb)\s+first\>'
                };
        case 'data conversion'
            keywords = {...
                '\<formulas?\>', ...
                '\<linearization\>', ...
                '\<conversions?\>', ...
                '\<calibrations?\>', ...
                '\<compensations?\>', ...
                '\<two''s\s+complements?\>',...
                '\<(?:measurement|output|raw)\s+(?:output|result|data|format)s?\>', ...
                '\<(?:adc|raw)\s+code\>', ...
                '\<(?:un)?signed\>', ...
                '\<byte\s+order\>', ...
                '\<endianness\>', ...
                '\<(?:msb|lsb|(?:most|least)\s+significant\s+bit)\>', ...
                '\<resolution\>', ...
                '\<sensitivity\>', ...
                '\<scale\s+factor\>', ...
                '\<offset\>', ...
                '\<gain\>', ...
                '\<full(?:-|\s+)scale\>'
                };
        case 'initialization and reset'
            keywords = {...
                '\<power management\>', ...
                '\<(?:initialization|initialisation)\>', ...
                '\<(?:initialize|initialise)\>', ...
                '\<init\.?\>', ...
                '\<(?:start|wake|power|set)(?:-|\s*)up(?:\s+(?:time|delay|sequence))?\>', ...
                '\<power(?:-|\s*)on(?:\s+(?:reset|sequence|delay))?\>', ...
                '\<boot(?:\s+(?:time|sequence))?\>', ...
                '\<(?:initial|configuration|recommended)\s+sequence\>', ...
                '\<after\s+(?:power(?:-|\s*)on|reset)\>', ...
                '\<before\s+accessing\>', ...
                '\<wait\s+after\s+reset\>', ...
                '\<(?:soft|software|hardware|device)\s+reset\>', ...
                '\<reset\s+(?:command|procedure|sequence)\>', ...
                '\<por\>', ...
                '\<(?:restore|factory)\s+defaults?\>', ...
                '\<(?:otp|nvm|trim)\s+reload\>' ...
                };
        case 'timing'
            keywords = {...
                '\<frequency\>', ...
                '\<timings?\>', ...
                '\<s|ms|ns|µs|sec\>', ...
                '\<(?:start|wake|power|set|cycle)(?:-|\s*)up\s*time\>', ...
                '\<(?:conversion|integration|measurement|acquisition|sampling|response)\s*time\>', ...
                '\<(?:rise(:?(?:-|\s*)up)|ramp(:?(?:-|\s*)up)?|high|fall(:?(?:-|\s*)down)?|low|hold|settling|wait(ing)?)\s*time\>', ...
                '\<(?:turn(?:-|\s*)(?:on|off)|change|switch)\s*time\>', ...
                '\<time(?:-|\s*)out\>', ...
                '\<period\>', ...
                '\<pulse\>', ...
                '\<delay\>', ...
                '\<(?:sample|sampling)\s+rate\>', ...
                '\<odr\>'
                };
        case 'interrupt alert'
            keywords = { ...
                '\<interrupts?\>', ...
                '\<irq\>', ...
                '\<alert\>', ...
                '\<alarm\>', ...
                '\<warning\>', ...
                '\<fault\>', ...
                '\<event\s+flag\>', ...
                '\<(?:high|low)\s+threshold\>', ...
                '\<(?:upper|lower)\s+limit\>', ...
                '\<hysteresis\>' ...
                };
        case 'fifo'
            keywords = { ...
                '\<fifo\>', ...
                '\<watermark\>', ...
                '\<burst\s+read\>', ...
                '\<frame\s+format\>', ...
                '\<sample\s+order\>' ...
                };
        otherwise
            error('Unknown option: %s', option);
    end
end