function [regIdx,result] = findPageRanges(pages, option)
%Score pages based on keyword counts according to the selected option,and extract the pages most relevant to that option.

    %% Initialization
    keywords = selectKeyword(option);
    result = struct();
    featureCountsArray = zeros(1,numel(pages));
    firstTitleLikePage = 0;
    
    %% 
    for i = 1:numel(pages)
        text = pages(i).markdown;
        tables = pages(i).tables;
        titleCount = 0;
        featureCounts = 0;
        if ~isempty(tables)
            for j = 1:numel(tables)
                table = tables(j).content;
                text = [text newline table];
            end
        end
        text = lower(text);
        
        titleCount = searchKeywords(text,keywords.title);
        featureCounts = searchKeywords(text,keywords.feature);
        disp(i); %-------------------debug---------------------------
        titleLike = titleCount ~=0;
        if titleLike && firstTitleLikePage ==0
            firstTitleLikePage = i;
        end
        result.pages(i).title_like = titleLike;
        result.pages(i).feature_counts = featureCounts;
        featureCountsArray(i) = featureCounts;
    end
    regIdx = selectRange(featureCountsArray,firstTitleLikePage);
end

function keywords = selectKeyword(option)
%select keywords depend on option
    keywords = struct();
    switch(option)
        case 'register'
            keywords.title = {...
                '^#*\s*\d+(?:\.\d+)*\s+reg(?:isters?)(?:\smaps?|\smapping|\sdescriptions?|\stable|\sdefinitions?)?$', ...
                '^#*\s*\d+(?:\.\d+)*\s+addr(?:ess)?(?:\smap|\sdescription)$',...
                '^#*\s*\d+(?:\.\d+)*\s+memory map$' ...
                };
            keywords.feature = {...
                'reg(?:isters?)\s+(?:name|pointer|addr(?:ess)?)', ...
                'bit field', ...
                'bits?\s*\d*', ...
                'hex', ...
                'decimal', ...
                'initial value', ...
                'default value',...
                'reset value',...
                '\<r\>', ...
                '\<w\>', ...
                'r/w', ...
                'w/r', ...
                '\<rw\>', ...
                '\<wr\>', ...
                'read/write', ...
                'read only', ...
                'write only', ...
                'readable', ...
                'writable', ...
                '(?<!all rights )\<reserved\>', ...
                '0x[0-9a-f]{2}', ...
                '\<[0-9a-fA-F]{2}h\>', ...
                '(?:[01]{4}\s?){2,4}'
            };
        case 'functional description'
            keywords.title = {...
                'function(?:al)? (?:description|overview)', ...
                'opera(?:tion|ting) mode', ...
                'initialization', ...
                'power management'
                };
            keywords.feature = {...
                'fifo', ...
                'interrupt', ...
                'calibration', ...
                'self test', ...
                'self-test', ...
                }
        case 'communications interface'
            keywords.title = {...
                'serial interface', ...
                'communication interface', ...
                'communication protocol', ...
                'i2c interface', ...
                'spi interface', ...
                'uart interface', ...
                'command set' ...
                };
            keywords.feature = {...
                'i2c', ...
                'spi', ...
                'uart', ...
                'two wire interface', ...
                'three wire interface', ...
                'four wire interface' ...
                }
        case 'coding example'
            keywords.title = { ...
                'code example', ...
                'programming example', ...
                'application example', ...
                'sample code', ...
                'driver example', ...
                'quick start', ...
                'getting started' ...
            };
            keywords.feature = { ...
                'reference driver', ...
                'programming guide', ...
                'software guide' ...
            };
        case 'all'
    end
end

function count = searchKeywords(text,keywords)
    count = 0;
    for i=1:numel(keywords)
        match = regexp(text,keywords{i},'lineanchors');
        count = count + numel(match);
        match = regexp(text,keywords{i},'match'); % ------------debug
        disp(match); % -----------------------------------------debug
    end
end

function pageRange = selectRange(arrayCounts,firstTitleLikePage)
%Extract page ranges longer than n which allows gaps of up to m pages with zero keyword counts.
% the page range starts with the chapter title page when it exists.
% e.g. 6 Register Mapping

    m = 2; % Maximum number of consecutive zero-valued pages allowed.
    n = 2; % Mimimum number of consecutive nonzero-valued pages allowed.
    negativeMask = (arrayCounts <= 0);
    d = diff([0 negativeMask 0]);
    zStartIdx = find(d == 1);             
    zEndIdx = find(d == -1) - 1;   
    
    invalid = (zEndIdx - zStartIdx + 1) > m;
    invalidStart = zStartIdx(invalid);
    invalidEnd = zEndIdx(invalid);
    startIdx = 1;
    pageRange = {};
    
    for i = 1:numel(invalidStart)
        endIdx = invalidStart(i) - 1;
        
        if endIdx-startIdx +1 > n && startIdx <= endIdx
            pageRange{end+1} = [startIdx endIdx];
        end
        
        startIdx = invalidEnd(i)+1;
    end
    
    if numel(arrayCounts)-startIdx + 1 > n
        pageRange{end+1} = [startIdx numel(arrayCounts)];
    end
    
    if firstTitleLikePage ~= 0
        mask = true(1,numel(pageRange));
        
        for i = 1:numel(pageRange)
            if all(firstTitleLikePage>pageRange{i})
                % Remove page ranges located entirely before the first title-like page.
                mask(i) = false;;
            end
        end
        
        if ~isempty(pageRange)
            pageRange = pageRange(mask);
            if ~isempty(pageRange)
                % Replace the start-page of the first valid page range with
                % the first title-like page
                pageRange{1}(1) = firstTitleLikePage;
            end
        end
    end
    for i = 1:numel(pageRange)
        pageRange{i} = pageRange{i}(1):pageRange{i}(2);
    end
end