function regMapJson = regMapExtractor(pages)
%UNTITLED13 Summary of this function goes here
%   Detailed explanation goes here

%% build respond format of LLM output
addressStr = struct( ...
    'hex', "", ...
    'decimal', "" ...
    );

valueStr(1) = struct( ...
    'value', "", ...
    'value_description', "" ...
    );

valueStr(2) = struct( ...
    'value', "", ...
    'value_description', "" ...
    );

fieldStr(1) = struct( ...
    'name_or_parameter', "", ...
    'field_description', "", ...
    'bit_start', 0, ...
    'bit_end', 0, ...
    'bit_width', 0, ...
    'values', valueStr, ...
    'is_reserved', false, ...
    'type_write_read', "" ...
    );

fieldStr(2) = struct( ...
    'name_or_parameter', "", ...
    'field_description', "", ...
    'bit_start', 0, ...
    'bit_end', 0, ...
    'bit_width', 0, ...
    'values', valueStr, ...
    'is_reserved', false, ...
    'type_write_read', "" ...
    );

sourceStr(1) = struct( ...
    'page_index', 0 ...
    );

sourceStr(2) = struct( ...
    'page_index', 0 ...
    );

registerStr(1) = struct( ...
    'index', 0, ...
    'name', "", ...
    'address', addressStr, ...
    'register_description', "", ...
    'width_bits', 0, ...
    'type_write_read', "", ...
    'bit_field', fieldStr, ...
    'category', "", ...
    'source', sourceStr, ...
    'default_value', "", ...
    'default_value_description', "" ...
    );

registerStr(2) = struct( ...
    'index', 0, ...
    'name', "", ...
    'address', addressStr, ...
    'register_description', "", ...
    'width_bits', 0, ...
    'type_write_read', "", ...
    'bit_field', fieldStr, ...
    'category', "", ...
    'source', sourceStr, ...
    'default_value', "", ...
    'default_value_description', "" ...
    );

output = struct( ...
    'Registers', registerStr ...
    );

%% AI-Register Map extractor
loadenv(".env");
apiKey = getenv("OPENAI_API_KEY");
modelName = "gpt-5-mini";
systemPrompt = fileread("prompt_regMapExtractor.txt");

pagesJson = jsonencode(pages);
context = pagesJson;
userPrompt = ['Context is provided as follows:' ...
newline ...
context ... 
newline ...
'Extract all registers only from the provided pages. ' ...
'Do not use any information outside these pages.'];

chat = openAIChat( ...
    systemPrompt, ...
    ResponseFormat = output, ...
    APIKey=apiKey, ...
    ModelName = modelName, ...
    TimeOut=90);

regMapJson = generate(chat,userPrompt,TimeOut=3000);
end