function result = searchToc(tocPages, option)
% Search TOC pages for chapter ranges matching a target category.
% Input:
%   tocPages (struct): TOC candidate pages returned by hasToc.
%   option (char|string): Target category. Supported values are
%       'register', 'functional description',
%       'communication interface', 'coding example', and 'all'.
%
% Output:
%   result (struct): Search result for the requested category. For a single
%       category, it contains the matched flag, page range, and matched TOC
%       lines. For 'all', it returns one result for each category.

    keywordsReg = { ...
        'reg',...
        'register', ...
        'register map', ...
        'register maps', ...
        'register description', ...
        'register descriptions', ...
        'register definition', ...
        'register definitions', ...
        'register summary', ...
        'register summaries', ...
        'register list', ...
        'register lists', ...
        'register table', ...
        'register tables', ...
        'register address', ...
        'register addresses', ...
        'addr', ...
        'address', ...
        'address map', ...
        'memory map', ...
        'bit field', ...
        'bit fields', ...
        'field description', ...
        'field descriptions', ...
        'register overview', ...
        'register reference' ...
    };

    keywordsFun = { ...
        'functional description', ...
        'functional descriptions', ...
        'function description', ...
        'function descriptions', ...
        'functional overview', ...
        'function overview', ...
        'operation description', ...
        'operation mode', ...
        'operation modes', ...
        'operating mode', ...
        'operating modes', ...
        'configuration', ...
        'initialization', ...
        'interrupt', ...
        'interrupts', ...
        'fifo', ...
        'calibration', ...
        'self test', ...
        'self-test', ...
        'power management' ...
    };

    keywordsCom = { ...
        'digital interfaces', ...
        'serial interface', ...
        'communication interface', ...
        'communication protocol', ...
        'command set', ...
        'i2c', ...
        'i2c interface', ...
        'i2c bus', ...
        'spi', ...
        'spi interface', ...
        'spi bus', ...
        'uart', ...
        'uart interface', ...
        'two wire interface', ...
        'two-wire interface', ...
        'three wire interface', ...
        'three-wire interface', ...
        'four wire interface', ...
        'four-wire interface' ...
    };

    keywordsEg = { ...
        'code example', ...
        'code examples', ...
        'programming example', ...
        'programming examples', ...
        'application example', ...
        'application examples', ...
        'usage example', ...
        'sample code', ...
        'driver example', ...
        'driver examples', ...
        'quick start', ...
        'getting started', ...
        'reference driver', ...
        'programming guide', ...
        'software guide'
    };

    option = lower(strtrim(char(option)));

    switch option
        case 'all'
            result.register = searchToc(tocPages, 'register');
            result.functional_description = searchToc(tocPages, 'functional description');
            result.communication_interface = searchToc(tocPages, 'communication interface');
            result.coding_example = searchToc(tocPages, 'coding example');
            return

        case 'register'
            keywords = keywordsReg;

        case 'functional description'
            keywords = keywordsFun;

        case 'communication interface'
            keywords = keywordsCom;

        case 'coding example'
            keywords = keywordsEg;

        otherwise
            error('Unsupported option: %s', option);
    end

    result = struct();
    keyLines = {};
    pageStart = 1;
    pageEnd = tocPages.total_pages;
    lastFoundPage = -999;
    lastFoundLine = -999;

    for i = 1:numel(tocPages.pages)
        text = tocPages.pages(i).content;
        lines = text2lines(text);

        for j = 1:numel(lines)
            found = false;
            thisLine = lines(j);
            match = detectTocPattern(thisLine) ~= 0;

            if match
                thisLine = lower(lines{j});
                for k = 1:numel(keywords)
                    found = matchPattern(thisLine, keywords{k});
                    if found
                        keyLines{end+1} = lines{j};
                        lastFoundPage = i;
                        lastFoundLine = j;
                        break
                    end
                end
            end
        end
    end

    isMatched = ~isempty(keyLines);
    foundEnd = false;

    if isMatched
        token = regexp(keyLines{1}, '\d+$', 'match', 'once');
        pageStart = str2double(token);

        text = tocPages.pages(lastFoundPage).content;
        lines = text2lines(text);

        if lastFoundLine < numel(lines)
            for i = lastFoundLine + 1:numel(lines)
                thisLine = lines(i);
                match = detectTocPattern(thisLine) ~= 0;
                if match
                    token = regexp(lines{i}, '\d+$', 'match', 'once');
                    pageEnd = str2double(token);
                    foundEnd = true;
                    break
                end
            end
        end

        if lastFoundPage < numel(tocPages.pages) && ~foundEnd
            for i = lastFoundPage + 1:numel(tocPages.pages)
                text = tocPages.pages(i).content;
                lines = text2lines(text);

                for j = 1:numel(lines)
                    thisLine = lines(j);
                    match = detectTocPattern(thisLine) ~= 0;
                    if match
                        token = regexp(lines{j}, '\d+$', 'match', 'once');
                        pageEnd = str2double(token);
                        foundEnd = true;
                        break
                    end
                end

                if foundEnd
                    break
                end
            end
        end
    end

    result.option = option;
    result.isMatched = isMatched;
    result.pageRange = [pageStart pageEnd];
    result.keyLines = keyLines;
end